// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uijvqvclplnutckllvri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpanZxdmNscGxudXRja2xsdnJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMzY3NjEsImV4cCI6MjA3MTkxMjc2MX0.CQ97l1MD_o3ZhrQY4242zJgki5rRkfyBZC1DY2u_zIo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});